language: python
before_install:
  - pip install --update pip
  - pip install poetry
install:
  - poetry install
script:
  - poetry run python3 -m unittest
deploy:
  provider: pypi
  server: https://test.pypi.org/legacy/
  username:
    secure: d9oA9YKsqdZiE0aloVj7mhZ35kZu1iTEl8mglH8re7kP73Zidr+WHyIDDDrj3amTr9wzJdzrqpcrZbKxQVFytMvVBRLtkRJAAw43xmXyj5/AIcm6TzgqGIpEwFSdruofNc0L+dqiU+ml04n3Grqv0ZGx7+68G/rkC5n20RYZX9Bf/SKsyqhR3u5fopbWfY1686rUBYaZT2UvhuYJAwe8e8FHtCO356XZAcrvFFO+6JWq9l0zizrB35pGVrKiFnQG8Ro0rtgxAv7GYQaloJ7aQp0WcRA1pjg19qJCV6vvTQh8IxgnCAb2kXqVWo/Po6Xtk9bN6VLqgmffIuvhEhjbMWGLzEbVBHTT0F0SUzvite+MgZRtNFXzbNVIV3iTEdGfqHXOxuPZyikd3eDcZAtX1knQJRts8+ZkGXDzEjAYMYXCZ5uqXbDNbYZOO3BMnPvj6s+YL4rZQQTRbAiiqaIp8nkCTrndv1wMEbzPWW4ei97zjJ/BKCVjqL05Gck41TxS1NX7VrXjk9IQWXBSqeAkp7D7QAV/PTxq4qu9TCqpuRQNZe7ZwuelAVKQ8o7JGU65J0meR63fQrxMoFpEUzkQi7ynUdW10aXNQ2OJWDxIOb3p/jkZp8cuf+IM6KvuKbw9YhAxy5OAV04Td+lEL//M/I7gCUH2Gbm8bZBmBcF7Wzs=
  password:
    secure: WJ3hXB54YvGS25HWrJlE4uMB+EOIk6LnOYmq93QvrOUX4YMI56mbXyTszvdj5P+dHuxz3MJJ+Yli7NMmRd/Vl2vQldH3j0PnIYnHoZplnrX9+gbk2wLPcGC10uNCZlYIRz/pjbwN+VtVULGd+ylI8hYrMiLWvMrPWQjR82Is2oer426MRghGes57BeJXITkDrQ90CFj+/YMnF2EXRHygOx/BhhtM1D1LAdI4xjIQ5sfLtD0/ZUMbB4CIG23X4pk4gb540fWSmKYSSu3nNhSsctLj+qmTY/NhBHgY76RKmOeX7Ev3oJo61JrSF7GL/hMXUcwCupjtSYBP8NvimyrEYWCsxBiWGq24XyNDxYFaCOrPPx6kvG8xHHSrx7kpubXtkhm0SKpH0IaQ47I+9PR0SfdSm64Q4uyTcpvODMf8ZBQySynnbRk4gpIF3FT7czYCTcvipKhSedi6bXpoFxCur5Lp/YHs31dcpOCEO29D4+A94KW+JXNmniusPE4ezemUMU0LegTUy1mn0TJrCMLegLW1CbtY0O92Bxdfs/llQKOi/uiDN8karS2ln+KG3Ld2XRKNlIeQGdaJ8FB4K16lcXgQQ0yTUVKEqurgMkSe4CJ6YURN3wgeuOMlkyfSpeaUwspBAyEFqLe/ONlXv4UzpRrRXp38iM70X/Scp8eGv5E=
